# Site settings
title:          otakijae
description:    "blog"
baseurl:        ""
url:            "https://otakijae.github.io"

remote_theme: chesterhow/tale

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         otakijae
  url:          https://otakijae.github.io
  email:        jh33836782@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
# permalink:      /:year:month:day/:title (default settings)
permalink:      /:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
